[package]
name = "test-tauri-app"
version = "0.1.0"
description = "mizu-pairrank"
authors = ["\u307f\u305a"]
edition = "2024"

[lib]
name = "test_tauri_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
tauri = { version = "2.11.3", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
