_commit: ff0efb1
_src_path: git@github.com:mizucopo/repo-template.git
author_email: mizu.copo@gmail.com
author_name: みず
node_version: '24'
project_description: 2つの候補を比較して順位付けするデスクトップアプリ
project_name: mizu-pairrank
project_version: 0.2.1
rust_version: stable
tauri_identifier: dev.mizu.pairrank
tauri_package_name: mizu-pairrank
tauri_product_name: mizu-pairrank
tauri_version: 0.2.1
use_chrome_extension: false
use_dependabot_github_actions: true
use_docker: false
use_gh_actions_pr_tag_check: false
use_gh_actions_release: false
use_mit_license: false
use_python: false
use_rust: false
use_tauri: true
repo_template_python_starters_created: false
repo_template_python_application_starter_created: false
repo_template_python_package_starter_names: []
repo_template_rust_starters_created: false
repo_template_chrome_starters_created: false
repo_template_tauri_starters_created: true
