_commit: afdb582
_src_path: git@github.com:mizucopo/repo-template.git
author_email: mizu.copo@gmail.com
author_name: みず
node_version: '24'
rust_version: stable
tauri_identifier: dev.mizu.pairrank
tauri_product_name: mizu-pairrank
tauri_version: 0.2.0
use_chrome_extension: false
use_dependabot_github_actions: true
use_docker: false
use_gh_actions_pr_tag_check: false
use_gh_actions_release: false
use_mit_license: false
use_python: false
use_rust: false
use_tauri: true
